image: docker

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  stage: test
  only:
    - staging
  script:
    - echo It should be running some test
  tags:
    - staging

step-deploy-staging:
  stage: deploy
  only:
    - staging
  variables:
    API_URL: ""
    GOOGLE_KEY: "ABCD"
    NEXT_APP_VERSION: "0.0.13"
  script:
    # - sudo docker image prune -f
    # - docker volume prune -f
    - docker-compose build
    - docker-compose down
    - docker-compose up -d
  tags:
    - staging
  environment: staging

step-deploy-prod:
  stage: deploy
  only:
    - production
  variables:
    API_URL: ""
  script:
    - sudo docker image prune -f
    - docker-compose build --no-cache
    - docker-compose up -d
  environment: production