name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      TAG: date + %s
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Test environment variables
        run: echo $TAG_NAME
        env:
          TAG_NAME: v${{ steps.date.outputs.date }}
          
      - uses: actions/checkout@v3
      - name: Login to image repository
        uses: docker/login-action@v2
        with:
              registry: registry.ropomoda.com
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build the Docker image 
        env:
          TAG_NAME: v${{ steps.date.outputs.date }}
        run: docker build . --file Dockerfile --tag frontend:$TAG_NAME

      - name: Push the Docker image
        env:
          TAG_NAME: v${{ steps.date.outputs.date }}
        run: docker push frontend:$TAG_NAME

